name: "Automated release"
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
      - run: deno install --config=./test/client/deno.json --entrypoint ./test/client/main.ts
      - run: deno install --config=./test/server/deno.json --entrypoint ./test/server/main.ts
      - run: deno test --allow-run --allow-net
      - run: deno lint
      - run: deno publish
